project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Multi-modal data integration and analysis"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Session 1
      - file: about.qmd
        text: Extra
      

format:
  html:
    light: lumen
    dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

