project:
  type: website
  output-dir: docs

website:
  title: "HDS_DataIntegration"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    light: minty
    dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

